wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727996845
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 13
      - 23
      4: 3.12.4
      5: 0.17.8
      6: 4.44.0
      8:
      - 3
      - 5
      12: ''
      13: windows-amd64
